### ISSUE TITLE
Gerar verificação do ip para não aceitar números acima de 255

### ISSUE THREAD

**Issue by gilvia-layana** [EngErick13/IPv6_Prefix_Pv#1]
![image](https://user-images.githubusercontent.com/43282405/206857612-5c23731b-e8ad-4d8d-beb2-6331966c200e.png)

**Comment by EngErick13** [comment]
Realmente Passou despercebido, irei adicionar isto no desenvolvimento

**Comment by EngErick13** [comment]
Atualizei o código, se possível avaliar e confirmar se o erro persiste.
Adicionei a importação "SYS" para interromper o código e enviar a msg de erro, em caso de não conformidade

**Comment by gilvia-layana** [comment]
Um novo problema foi verificado, conforme o print abaixo: 
![image](https://user-images.githubusercontent.com/43282405/207047062-f9fe2772-d713-46cf-bd47-233950505bf4.png)
é necessário uma verificação do tipo de equipamento informado.

**Comment by gilvia-layana** [comment]
Realizado testes após as modificações e os erros foram corrigidos.
